"""Add fields (about_me and last_me) in user model

Revision ID: 343fe308659e
Revises: d48703ad2bca
Create Date: 2021-10-27 10:41:59.131079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343fe308659e'
down_revision = 'd48703ad2bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'last_seen')
    op.drop_column('post', 'about_me')
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.add_column('post', sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
    op.add_column('post', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
