"""Add fields (about_me and last_me) in user model

Revision ID: d48703ad2bca
Revises: 90e9200fbd31
Create Date: 2021-10-27 10:30:47.504365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48703ad2bca'
down_revision = '90e9200fbd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('post', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'last_seen')
    op.drop_column('post', 'about_me')
    # ### end Alembic commands ###
